### ISSUE TITLE
Interested on the format and a few questions

### ISSUE THREAD

**Issue by AngheloAlf** [Tilka/hvqm2#1]
Hi!

I'm interested on the HVQM2 video format and recently I found this repo.
I wanted to ask you, how did you manage to made this tool? Did you reverse engineered the libhvqm2.a library?

Also, this repository doesn't have a license or anything similar. What's your stance on other people reusing this code? Either directly or as a reference.

Thanks for your time.

**Comment by Tilka** [comment]
It's reverse engineered, but I don't remember from what.

I've added a license file (MIT).

**Comment by AngheloAlf** [comment]
I see, that's nice to know.

Thanks for the response!
